# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/analyzer/bytecode_analyzer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.analyzer import reporter_pb2 as protos_dot_analyzer_dot_reporter__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/analyzer/bytecode_analyzer.proto',
  package='analyzer',
  syntax='proto3',
  serialized_pb=_b('\n\'protos/analyzer/bytecode_analyzer.proto\x12\x08\x61nalyzer\x1a\x1eprotos/analyzer/reporter.proto\"\x92\x01\n\x17\x42yteCodeAnalysisRequest\x12/\n\rbefore_change\x18\x01 \x01(\x0b\x32\x18.analyzer.AnalysisTarget\x12.\n\x0c\x61\x66ter_change\x18\x02 \x01(\x0b\x32\x18.analyzer.AnalysisTarget\x12\x16\n\x0e\x64iffs_log_path\x18\x03 \x01(\t\"\xe1\x02\n\x18\x42yteCodeAnalysisResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x17\n\x0f\x63\x66g_before_path\x18\x03 \x01(\t\x12\x16\n\x0e\x63\x66g_after_path\x18\x04 \x01(\t\x12\x17\n\x0fssg_before_path\x18\x05 \x01(\t\x12\x16\n\x0essg_after_path\x18\x06 \x01(\t\x12\x19\n\x11\x63\x66g_abstract_path\x18\x07 \x01(\t\x12\x19\n\x11ssg_abstract_path\x18\x08 \x01(\t\x12\"\n\x1a\x63\x66g_edge_lists_before_path\x18\t \x01(\t\x12!\n\x19\x63\x66g_edge_lists_after_path\x18\n \x01(\t\x12\"\n\x1assg_edge_lists_before_path\x18\x0b \x01(\t\x12!\n\x19ssg_edge_lists_after_path\x18\x0c \x01(\tB\x1cZ\x1aprotobuf/analyzer;analyzerb\x06proto3')
  ,
  dependencies=[protos_dot_analyzer_dot_reporter__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BYTECODEANALYSISREQUEST = _descriptor.Descriptor(
  name='ByteCodeAnalysisRequest',
  full_name='analyzer.ByteCodeAnalysisRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='before_change', full_name='analyzer.ByteCodeAnalysisRequest.before_change', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='after_change', full_name='analyzer.ByteCodeAnalysisRequest.after_change', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='diffs_log_path', full_name='analyzer.ByteCodeAnalysisRequest.diffs_log_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=232,
)


_BYTECODEANALYSISRESPONSE = _descriptor.Descriptor(
  name='ByteCodeAnalysisResponse',
  full_name='analyzer.ByteCodeAnalysisResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='analyzer.ByteCodeAnalysisResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='analyzer.ByteCodeAnalysisResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cfg_before_path', full_name='analyzer.ByteCodeAnalysisResponse.cfg_before_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cfg_after_path', full_name='analyzer.ByteCodeAnalysisResponse.cfg_after_path', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ssg_before_path', full_name='analyzer.ByteCodeAnalysisResponse.ssg_before_path', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ssg_after_path', full_name='analyzer.ByteCodeAnalysisResponse.ssg_after_path', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cfg_abstract_path', full_name='analyzer.ByteCodeAnalysisResponse.cfg_abstract_path', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ssg_abstract_path', full_name='analyzer.ByteCodeAnalysisResponse.ssg_abstract_path', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cfg_edge_lists_before_path', full_name='analyzer.ByteCodeAnalysisResponse.cfg_edge_lists_before_path', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cfg_edge_lists_after_path', full_name='analyzer.ByteCodeAnalysisResponse.cfg_edge_lists_after_path', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ssg_edge_lists_before_path', full_name='analyzer.ByteCodeAnalysisResponse.ssg_edge_lists_before_path', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ssg_edge_lists_after_path', full_name='analyzer.ByteCodeAnalysisResponse.ssg_edge_lists_after_path', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=588,
)

_BYTECODEANALYSISREQUEST.fields_by_name['before_change'].message_type = protos_dot_analyzer_dot_reporter__pb2._ANALYSISTARGET
_BYTECODEANALYSISREQUEST.fields_by_name['after_change'].message_type = protos_dot_analyzer_dot_reporter__pb2._ANALYSISTARGET
DESCRIPTOR.message_types_by_name['ByteCodeAnalysisRequest'] = _BYTECODEANALYSISREQUEST
DESCRIPTOR.message_types_by_name['ByteCodeAnalysisResponse'] = _BYTECODEANALYSISRESPONSE

ByteCodeAnalysisRequest = _reflection.GeneratedProtocolMessageType('ByteCodeAnalysisRequest', (_message.Message,), dict(
  DESCRIPTOR = _BYTECODEANALYSISREQUEST,
  __module__ = 'protos.analyzer.bytecode_analyzer_pb2'
  # @@protoc_insertion_point(class_scope:analyzer.ByteCodeAnalysisRequest)
  ))
_sym_db.RegisterMessage(ByteCodeAnalysisRequest)

ByteCodeAnalysisResponse = _reflection.GeneratedProtocolMessageType('ByteCodeAnalysisResponse', (_message.Message,), dict(
  DESCRIPTOR = _BYTECODEANALYSISRESPONSE,
  __module__ = 'protos.analyzer.bytecode_analyzer_pb2'
  # @@protoc_insertion_point(class_scope:analyzer.ByteCodeAnalysisResponse)
  ))
_sym_db.RegisterMessage(ByteCodeAnalysisResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\032protobuf/analyzer;analyzer'))
# @@protoc_insertion_point(module_scope)
