# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos.analyzer import reporter_pb2 as protos_dot_analyzer_dot_reporter__pb2


class AnalysisStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetReports = channel.unary_unary(
                '/analyzer.Analysis/GetReports',
                request_serializer=protos_dot_analyzer_dot_reporter__pb2.AnalysisRequest.SerializeToString,
                response_deserializer=protos_dot_analyzer_dot_reporter__pb2.AnalysisResponse.FromString,
                )
        self.GetStructureReport = channel.unary_unary(
                '/analyzer.Analysis/GetStructureReport',
                request_serializer=protos_dot_analyzer_dot_reporter__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_analyzer_dot_reporter__pb2.Empty.FromString,
                )
        self.GetSemanticReport = channel.unary_unary(
                '/analyzer.Analysis/GetSemanticReport',
                request_serializer=protos_dot_analyzer_dot_reporter__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_analyzer_dot_reporter__pb2.Empty.FromString,
                )
        self.GetAbstractReport = channel.unary_unary(
                '/analyzer.Analysis/GetAbstractReport',
                request_serializer=protos_dot_analyzer_dot_reporter__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_analyzer_dot_reporter__pb2.Empty.FromString,
                )


class AnalysisServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetReports(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStructureReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSemanticReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAbstractReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalysisServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetReports': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReports,
                    request_deserializer=protos_dot_analyzer_dot_reporter__pb2.AnalysisRequest.FromString,
                    response_serializer=protos_dot_analyzer_dot_reporter__pb2.AnalysisResponse.SerializeToString,
            ),
            'GetStructureReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStructureReport,
                    request_deserializer=protos_dot_analyzer_dot_reporter__pb2.Empty.FromString,
                    response_serializer=protos_dot_analyzer_dot_reporter__pb2.Empty.SerializeToString,
            ),
            'GetSemanticReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSemanticReport,
                    request_deserializer=protos_dot_analyzer_dot_reporter__pb2.Empty.FromString,
                    response_serializer=protos_dot_analyzer_dot_reporter__pb2.Empty.SerializeToString,
            ),
            'GetAbstractReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAbstractReport,
                    request_deserializer=protos_dot_analyzer_dot_reporter__pb2.Empty.FromString,
                    response_serializer=protos_dot_analyzer_dot_reporter__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analyzer.Analysis', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Analysis(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetReports(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/analyzer.Analysis/GetReports',
            protos_dot_analyzer_dot_reporter__pb2.AnalysisRequest.SerializeToString,
            protos_dot_analyzer_dot_reporter__pb2.AnalysisResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStructureReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/analyzer.Analysis/GetStructureReport',
            protos_dot_analyzer_dot_reporter__pb2.Empty.SerializeToString,
            protos_dot_analyzer_dot_reporter__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSemanticReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/analyzer.Analysis/GetSemanticReport',
            protos_dot_analyzer_dot_reporter__pb2.Empty.SerializeToString,
            protos_dot_analyzer_dot_reporter__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAbstractReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/analyzer.Analysis/GetAbstractReport',
            protos_dot_analyzer_dot_reporter__pb2.Empty.SerializeToString,
            protos_dot_analyzer_dot_reporter__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
