# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos.analyzer import source_code_analyzer_pb2 as protos_dot_analyzer_dot_source__code__analyzer__pb2


class TsSourceCodeAnalysisStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyseSourceCode = channel.unary_unary(
                '/analyzer.TsSourceCodeAnalysis/AnalyseSourceCode',
                request_serializer=protos_dot_analyzer_dot_source__code__analyzer__pb2.SourceCodeAnalysisRequest.SerializeToString,
                response_deserializer=protos_dot_analyzer_dot_source__code__analyzer__pb2.SourceCodeAnalysisResponse.FromString,
                )


class TsSourceCodeAnalysisServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyseSourceCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TsSourceCodeAnalysisServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyseSourceCode': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyseSourceCode,
                    request_deserializer=protos_dot_analyzer_dot_source__code__analyzer__pb2.SourceCodeAnalysisRequest.FromString,
                    response_serializer=protos_dot_analyzer_dot_source__code__analyzer__pb2.SourceCodeAnalysisResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analyzer.TsSourceCodeAnalysis', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TsSourceCodeAnalysis(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyseSourceCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/analyzer.TsSourceCodeAnalysis/AnalyseSourceCode',
            protos_dot_analyzer_dot_source__code__analyzer__pb2.SourceCodeAnalysisRequest.SerializeToString,
            protos_dot_analyzer_dot_source__code__analyzer__pb2.SourceCodeAnalysisResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
